/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ClienteDAO;
import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author sonho
 */
public class RemoverClienteView extends javax.swing.JFrame {

    ClienteDAO cliDAO = new ClienteDAO();

    /**
     * Creates new form RemoverProdutoView
     */
    public RemoverClienteView() {
        initComponents();
        this.setTitle("Remover Cliente");
        decoracao();
    }

    public void exibirTela() {
        this.setVisible(true);
    }

    private void decoracao() {
        getContentPane().setBackground(Color.decode("#3f3f46"));
        lbInserirCodigo.setForeground(Color.decode("#fafaf9"));
        lbTitulo.setForeground(Color.decode("#fafaf9"));
        tfCPF.setBackground(Color.decode("#f3f4f6"));
        tfCPF.setForeground(Color.decode("#18181b"));
        btRemover.setBackground(Color.decode("#38bdf8"));
        btRemover.setForeground(Color.decode("#fafaf9"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        tfCPF = new javax.swing.JTextField();
        lbInserirCodigo = new javax.swing.JLabel();
        btRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Remover Cliente");

        lbInserirCodigo.setText("Insira o CPF do cliente");

        btRemover.setText("Remover");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbInserirCodigo)
                            .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btRemover)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(lbTitulo)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbTitulo)
                .addGap(33, 33, 33)
                .addComponent(lbInserirCodigo)
                .addGap(8, 8, 8)
                .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btRemover)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void adicionarAcaoRemover(ActionListener action) {
        btRemover.addActionListener(action);
    }
    
    public String getCPF() {
        return tfCPF.getText();
    }
    
    public boolean confirmarRemocao() {
        int confirmar =  mostrarMensagemConfirmacao();
        return confirmar == JOptionPane.YES_OPTION;
    }
    
    private int mostrarMensagemConfirmacao() {
        return JOptionPane.showConfirmDialog(null,
                "Deseja excluir este cliente do banco de dados?",
                "Apagar Cliente",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
    }

    public void mostrarAviso(String mensagem, String tituloAviso) {
        JOptionPane.showMessageDialog(null, mensagem, tituloAviso, JOptionPane.WARNING_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRemover;
    private javax.swing.JLabel lbInserirCodigo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField tfCPF;
    // End of variables declaration//GEN-END:variables
}
